pub(super) const NO_FILE_MAP: [(&str, &str); 0] = [];

pub(super) const CONCEPT1_FILE_MAP: [(&str, &str); 17] = [
    ("pointer.cur", "arrow.cur"),
    ("help.cur", "help.cur"),
    ("working.ani", "working.ani"),
    ("busy.ani", "busy.ani"),
    ("precision.cur", "precision.cur"),
    ("beam.cur", "beam.cur"),
    ("handwriting.cur", "pen.cur"),
    ("unavailable.cur", "unavailable.cur"),
    ("vert.cur", "vert.cur"),
    ("horz.cur", "horz.cur"),
    ("dgn1.cur", "dgnl.cur"),
    ("dgn2.cur", "dgnr.cur"),
    ("move.cur", "move.cur"),
    ("alternate.cur", "up.cur"),
    ("link.cur", "link.cur"),
    ("person.cur", "person.cur"),
    ("pin.cur", "pin.cur"),
];

pub(super) const ARCHIVE_FILE_MAP: [(&str, &str); 17] = [
    ("pointer.cur", "arrow.cur"),
    ("help.cur", "help.cur"),
    ("working.ani", "appstarting.ani"),
    ("busy.ani", "wait.ani"),
    ("precision.cur", "crosshair.cur"),
    ("beam.cur", "ibeam.cur"),
    ("handwriting.cur", "nwpen.cur"),
    ("unavailable.cur", "no.cur"),
    ("vert.cur", "sizens.cur"),
    ("horz.cur", "sizewe.cur"),
    ("dgn1.cur", "sizenwse.cur"),
    ("dgn2.cur", "sizenesw.cur"),
    ("move.cur", "sizeall.cur"),
    ("alternate.cur", "uparrow.cur"),
    ("link.cur", "hand.cur"),
    ("person.cur", "person.cur"),
    ("pin.cur", "pin.cur"),
];

pub(super) const ANTIDEN_FILE_MAP: [(&str, &str); 17] = [
    ("pointer.cur", "Normal.cur"),
    ("help.cur", "Help.cur"),
    ("working.ani", "Working.ani"),
    ("busy.ani", "Busy.ani"),
    ("precision.cur", "Precision.cur"),
    ("beam.cur", "Text.cur"),
    ("handwriting.cur", "Handwriting.cur"),
    ("unavailable.cur", "Unavailable.cur"),
    ("vert.cur", "Vertical Resize.cur"),
    ("horz.cur", "Horizontal Resize.cur"),
    ("dgn1.cur", "Diagonal Resize 1.cur"),
    ("dgn2.cur", "Diagonal Resize 2.cur"),
    ("move.cur", "Move.cur"),
    ("alternate.cur", "Alternate.cur"),
    ("link.cur", "Link.cur"),
    ("person.cur", "Person.cur"),
    ("pin.cur", "Pin.cur"),
];

pub(super) const BREEZE_PLASMA_FILE_MAP: [(&str, &str); 17] = [
    ("pointer.cur", "default.cur"),
    ("help.cur", "help.cur"),
    ("working.ani", "progress.ani"),
    ("busy.ani", "wait.ani"),
    ("precision.cur", "crosshair.cur"),
    ("beam.cur", "text.cur"),
    ("handwriting.cur", "pencil.cur"),
    ("unavailable.cur", "not-allowed.cur"),
    ("vert.cur", "size_ver.cur"),
    ("horz.cur", "size_hor.cur"),
    ("dgn1.cur", "size_fdiag.cur"),
    ("dgn2.cur", "size_bdiag.cur"),
    ("move.cur", "all-scroll.cur"),
    ("alternate.cur", "center_ptr.cur"),
    ("link.cur", "pointer.cur"),
    ("person.cur", "default.cur"),
    ("pin.cur", "default.cur"),
];

pub(super) const TAHOE_SHADOW_FILE_MAP: [(&str, &str); 17] = [
    ("pointer.cur", "arrowS.cur"),
    ("help.cur", "helpS.cur"),
    ("working.ani", "waitS.ani"),
    ("busy.ani", "busyS.ani"),
    ("precision.cur", "crossS.cur"),
    ("beam.cur", "beamS.cur"),
    ("handwriting.cur", "penS.cur"),
    ("unavailable.cur", "noS.cur"),
    ("vert.cur", "HsizeS.cur"),
    ("horz.cur", "VsizeS.cur"),
    ("dgn1.cur", "D2sizeS.cur"),
    ("dgn2.cur", "D1sizeS.cur"),
    ("move.cur", "moveS.cur"),
    ("alternate.cur", "upS.cur"),
    ("link.cur", "linkS.cur"),
    ("person.cur", "personS.cur"),
    ("pin.cur", "locationS.cur"),
];

pub(super) const VISION_FILE_MAP: [(&str, &str); 17] = [
    ("pointer.cur", "pointer.cur"),
    ("help.cur", "help.cur"),
    ("working.ani", "work.ani"),
    ("busy.ani", "busy.ani"),
    ("precision.cur", "cross.cur"),
    ("beam.cur", "text.cur"),
    ("handwriting.cur", "handwriting.cur"),
    ("unavailable.cur", "unavailiable.cur"),
    ("vert.cur", "vert.cur"),
    ("horz.cur", "horz.cur"),
    ("dgn1.cur", "dgn1.cur"),
    ("dgn2.cur", "dgn2.cur"),
    ("move.cur", "move.cur"),
    ("alternate.cur", "alternate.cur"),
    ("link.cur", "link.cur"),
    ("person.cur", "pin.cur"),
    ("pin.cur", "person.cur"),
];

pub(super) const BIBATA_FILE_MAP: [(&str, &str); 17] = [
    ("pointer.cur", "Pointer.cur"),
    ("help.cur", "Help.cur"),
    ("working.ani", "Work.ani"),
    ("busy.ani", "Busy.ani"),
    ("precision.cur", "Cross.cur"),
    ("beam.cur", "Text.cur"),
    ("handwriting.cur", "Handwriting.cur"),
    ("unavailable.cur", "Unavailable.cur"),
    ("vert.cur", "Vert.cur"),
    ("horz.cur", "Horz.cur"),
    ("dgn1.cur", "Dgn1.cur"),
    ("dgn2.cur", "Dgn2.cur"),
    ("move.cur", "Move.cur"),
    ("alternate.cur", "Alternate.cur"),
    ("link.cur", "Link.cur"),
    ("person.cur", "Person.cur"),
    ("pin.cur", "Pin.cur"),
];

pub(super) const POSY_FILE_MAP: [(&str, &str); 17] = [
    ("pointer.cur", "Posy cursor.cur"),
    ("help.cur", "Posy help.cur"),
    ("working.ani", "Posy background max 96.ani"),
    ("busy.ani", "Posy wait max 96.ani"),
    ("precision.cur", "Posy precise.cur"),
    ("beam.cur", "Posy beam.cur"),
    ("handwriting.cur", "Posy pen.cur"),
    ("unavailable.cur", "Posy forbidden.cur"),
    ("vert.cur", "Posy size NS.cur"),
    ("horz.cur", "Posy size EW.cur"),
    ("dgn1.cur", "Posy size NwSe.cur"),
    ("dgn2.cur", "Posy size NeSw.cur"),
    ("move.cur", "Posy move.cur"),
    ("alternate.cur", "Posy alt.cur"),
    ("link.cur", "Posy hand.cur"),
    ("person.cur", "Posy cursor.cur"),
    ("pin.cur", "Posy cursor.cur"),
];

pub(super) const POSY_BLACK_FILE_MAP: [(&str, &str); 17] = [
    ("pointer.cur", "Posy Black default.cur"),
    ("help.cur", "Posy Black help.cur"),
    ("working.ani", "Posy Black background max 96.ani"),
    ("busy.ani", "Posy wait max 96.ani"),
    ("precision.cur", "Posy precise.cur"),
    ("beam.cur", "Posy beam.cur"),
    ("handwriting.cur", "Posy Black pen.cur"),
    ("unavailable.cur", "Posy forbidden.cur"),
    ("vert.cur", "Posy Black size NS.cur"),
    ("horz.cur", "Posy Black size EW.cur"),
    ("dgn1.cur", "Posy Black size NwSe.cur"),
    ("dgn2.cur", "Posy Black size NeSw.cur"),
    ("move.cur", "Posy move.cur"),
    ("alternate.cur", "Posy alt.cur"),
    ("link.cur", "Posy hand.cur"),
    ("person.cur", "Posy Black default.cur"),
    ("pin.cur", "Posy Black default.cur"),
];

pub(super) const NERO_FILE_MAP: [(&str, &str); 17] = [
    ("pointer.cur", "[CC] Normal v1 HD.ani"),
    ("help.cur", "[CC] Help v1 HD.ani"),
    ("working.ani", "[CC] Working v1 HD.ani"),
    ("busy.ani", "[CC] Busy v1 HD.ani"),
    ("precision.cur", "[CC] Precision v1 HD.ani"),
    ("beam.cur", "[CC] Text v1 HD.ani"),
    ("handwriting.cur", "[CC] Handwrite v1 HD.ani"),
    ("unavailable.cur", "[CC] Unavailable v1 HD.ani"),
    ("vert.cur", "[CC] VertRes v1 HD.ani"),
    ("horz.cur", "[CC] HoriRes v1 HD.ani"),
    ("dgn1.cur", "[CC] DiaRes1 v1 HD.ani"),
    ("dgn2.cur", "[CC] DiaRes2 v1 HD.ani"),
    ("move.cur", "[CC] Move v1 HD.ani"),
    ("alternate.cur", "[CC] Alternate v1 HD.ani"),
    ("link.cur", "[CC] Link v1 HD.ani"),
    ("person.cur", "[CC] Person v1 HD.ani"),
    ("pin.cur", "[CC] Location v1 HD.ani"),
];

pub(super) const BREEZE_NORD_FILE_MAP: [(&str, &str); 17] = [
    ("pointer.cur", "1 normal select.cur"),
    ("help.cur", "2 help.cur"),
    ("working.ani", "3 working in background.ani"),
    ("busy.ani", "4 busy.ani"),
    ("precision.cur", "5 precision select.cur"),
    ("beam.cur", "6 text select.cur"),
    ("handwriting.cur", "5 precision select.cur"),
    ("unavailable.cur", "7 unavailable.cur"),
    ("vert.cur", "8 vertical resize.cur"),
    ("horz.cur", "9 horizontal resize.cur"),
    ("dgn1.cur", "10 diagonal resize 1.cur"),
    ("dgn2.cur", "11 diagonal resize 2.cur"),
    ("move.cur", "12 move.cur"),
    ("alternate.cur", "13 alternative select.cur"),
    ("link.cur", "14 link select.cur"),
    ("person.cur", "1 normal select.cur"),
    ("pin.cur", "1 normal select.cur"),
];

pub(super) const ALKANO_EMERALD_FILE_MAP: [(&str, &str); 17] = [
    ("pointer.cur", "Emerald Normal Select.cur"),
    ("help.cur", "Emerald Help Select.cur"),
    ("working.ani", "Emerald Working in Background.ani"),
    ("busy.ani", "Emerald Busy.ani"),
    ("precision.cur", "Emerald Precision Select.ani"),
    ("beam.cur", "Emerald Text Select.ani"),
    ("handwriting.cur", "Emerald Handwriting.cur"),
    ("unavailable.cur", "Emerald Unavailable.cur"),
    ("vert.cur", "Emerald Vertical Resize.ani"),
    ("horz.cur", "Emerald Horizontal Resize.ani"),
    ("dgn1.cur", "Emerald Diagonal Resize 1.ani"),
    ("dgn2.cur", "Emerald Diagonal Resize 2.ani"),
    ("move.cur", "Emerald Move.cur"),
    ("alternate.cur", "Emerald Alternate Select.cur"),
    ("link.cur", "Emerald Link Select.cur"),
    ("person.cur", "Emerald Person Select.cur"),
    ("pin.cur", "Emerald Location Select.cur"),
];

pub(super) const COMIX_FILE_MAP: [(&str, &str); 17] = [
    ("pointer.cur", "Arrow.cur"),
    ("help.cur", "Help.cur"),
    ("working.ani", "AppStarting.ani"),
    ("busy.ani", "Wait.ani"),
    ("precision.cur", "Cross.ani"),
    ("beam.cur", "IBeam.ani"),
    ("handwriting.cur", "Handwriting.cur"),
    ("unavailable.cur", "NO.cur"),
    ("vert.cur", "SizeNS.cur"),
    ("horz.cur", "SizeWE.cur"),
    ("dgn1.cur", "SizeNWSE.cur"),
    ("dgn2.cur", "SizeNESW.cur"),
    ("move.cur", "SizeAll.cur"),
    ("alternate.cur", "UpArrow.cur"),
    ("link.cur", "Hand.cur"),
    ("person.cur", "Hand2.cur"),
    ("pin.cur", "Copy.cur"),
];
