package dev.screengoated.toolbox.mobile.model

object LanguageCatalog {
    private val entries = listOf(
        "Abkhazian" to "AB",
        "Afar" to "AA",
        "Afrikaans" to "AF",
        "Akan" to "AK",
        "Albanian" to "SQ",
        "Amharic" to "AM",
        "Arabic" to "AR",
        "Aragonese" to "AN",
        "Armenian" to "HY",
        "Assamese" to "AS",
        "Avaric" to "AV",
        "Avestan" to "AE",
        "Aymara" to "AY",
        "Azerbaijani" to "AZ",
        "Bambara" to "BM",
        "Bashkir" to "BA",
        "Basque" to "EU",
        "Belarusian" to "BE",
        "Bengali" to "BN",
        "Bislama" to "BI",
        "Bosnian" to "BS",
        "Breton" to "BR",
        "Bulgarian" to "BG",
        "Burmese" to "MY",
        "Catalan" to "CA",
        "Chamorro" to "CH",
        "Chechen" to "CE",
        "Chinese" to "ZH",
        "Church Slavic" to "CU",
        "Chuvash" to "CV",
        "Cornish" to "KW",
        "Corsican" to "CO",
        "Cree" to "CR",
        "Croatian" to "HR",
        "Czech" to "CS",
        "Danish" to "DA",
        "Dhivehi" to "DV",
        "Dutch" to "NL",
        "Dzongkha" to "DZ",
        "English" to "EN",
        "Esperanto" to "EO",
        "Estonian" to "ET",
        "Ewe" to "EE",
        "Faroese" to "FO",
        "Fijian" to "FJ",
        "Finnish" to "FI",
        "French" to "FR",
        "Fulah" to "FF",
        "Galician" to "GL",
        "Ganda" to "LG",
        "Georgian" to "KA",
        "German" to "DE",
        "Guarani" to "GN",
        "Gujarati" to "GU",
        "Haitian" to "HT",
        "Hausa" to "HA",
        "Hebrew" to "HE",
        "Herero" to "HZ",
        "Hindi" to "HI",
        "Hiri Motu" to "HO",
        "Hungarian" to "HU",
        "Icelandic" to "IS",
        "Ido" to "IO",
        "Igbo" to "IG",
        "Indonesian" to "ID",
        "Interlingua" to "IA",
        "Interlingue" to "IE",
        "Inuktitut" to "IU",
        "Inupiaq" to "IK",
        "Irish" to "GA",
        "Italian" to "IT",
        "Japanese" to "JA",
        "Javanese" to "JV",
        "Kalaallisut" to "KL",
        "Kannada" to "KN",
        "Kanuri" to "KR",
        "Kashmiri" to "KS",
        "Kazakh" to "KK",
        "Khmer" to "KM",
        "Kikuyu" to "KI",
        "Kinyarwanda" to "RW",
        "Kirghiz" to "KY",
        "Komi" to "KV",
        "Kongo" to "KG",
        "Korean" to "KO",
        "Kuanyama" to "KJ",
        "Kurdish" to "KU",
        "Lao" to "LO",
        "Latin" to "LA",
        "Latvian" to "LV",
        "Limburgan" to "LI",
        "Lingala" to "LN",
        "Lithuanian" to "LT",
        "Luba-Katanga" to "LU",
        "Luxembourgish" to "LB",
        "Macedonian" to "MK",
        "Malagasy" to "MG",
        "Malay" to "MS",
        "Malayalam" to "ML",
        "Maltese" to "MT",
        "Manx" to "GV",
        "Maori" to "MI",
        "Marathi" to "MR",
        "Marshallese" to "MH",
        "Modern Greek" to "EL",
        "Mongolian" to "MN",
        "Nauru" to "NA",
        "Navajo" to "NV",
        "Ndonga" to "NG",
        "Nepali" to "NE",
        "North Ndebele" to "ND",
        "Northern Sami" to "SE",
        "Norwegian" to "NO",
        "Norwegian Bokmål" to "NB",
        "Norwegian Nynorsk" to "NN",
        "Nyanja" to "NY",
        "Occitan" to "OC",
        "Ojibwa" to "OJ",
        "Oriya" to "OR",
        "Oromo" to "OM",
        "Ossetian" to "OS",
        "Pali" to "PI",
        "Panjabi" to "PA",
        "Persian" to "FA",
        "Polish" to "PL",
        "Portuguese" to "PT",
        "Pushto" to "PS",
        "Quechua" to "QU",
        "Romanian" to "RO",
        "Romansh" to "RM",
        "Rundi" to "RN",
        "Russian" to "RU",
        "Samoan" to "SM",
        "Sango" to "SG",
        "Sanskrit" to "SA",
        "Sardinian" to "SC",
        "Scottish Gaelic" to "GD",
        "Serbian" to "SR",
        "Serbo-Croatian" to "SH",
        "Shona" to "SN",
        "Sichuan Yi" to "II",
        "Sindhi" to "SD",
        "Sinhala" to "SI",
        "Slovak" to "SK",
        "Slovenian" to "SL",
        "Somali" to "SO",
        "South Ndebele" to "NR",
        "Southern Sotho" to "ST",
        "Spanish" to "ES",
        "Sundanese" to "SU",
        "Swahili" to "SW",
        "Swati" to "SS",
        "Swedish" to "SV",
        "Tagalog" to "TL",
        "Tahitian" to "TY",
        "Tajik" to "TG",
        "Tamil" to "TA",
        "Tatar" to "TT",
        "Telugu" to "TE",
        "Thai" to "TH",
        "Tibetan" to "BO",
        "Tigrinya" to "TI",
        "Tonga" to "TO",
        "Tsonga" to "TS",
        "Tswana" to "TN",
        "Turkish" to "TR",
        "Turkmen" to "TK",
        "Twi" to "TW",
        "Uighur" to "UG",
        "Ukrainian" to "UK",
        "Urdu" to "UR",
        "Uzbek" to "UZ",
        "Venda" to "VE",
        "Vietnamese" to "VI",
        "Volapük" to "VO",
        "Walloon" to "WA",
        "Welsh" to "CY",
        "Western Frisian" to "FY",
        "Wolof" to "WO",
        "Xhosa" to "XH",
        "Yiddish" to "YI",
        "Yoruba" to "YO",
        "Zhuang" to "ZA",
        "Zulu" to "ZU",
    )

    private val codeByName = entries.toMap()

    val names: List<String> = entries.map { it.first }

    fun codeForName(name: String): String {
        return codeByName[name] ?: name.trim().take(2).uppercase().ifBlank { "EN" }
    }
}
