import { useAppEffects } from "@/hooks/useAppEffects";
import { useCloseProject } from "@/hooks/useCloseProject";
import { useEditorInteractions } from "@/hooks/useEditorInteractions";

type AppLateEffectsArgs = Record<string, any>;

export function useAppLateEffects(args: AppLateEffectsArgs) {
  const {
    backgroundConfig,
    beginBatch,
    canRedo,
    canUndo,
    canvasRef,
    commitBatch,
    composition,
    currentAudio,
    currentMicAudio,
    currentProjectId,
    currentRawMicAudioPath,
    currentRawVideoPath,
    currentRawWebcamVideoPath,
    currentRecordingMode,
    currentTime,
    currentVideo,
    currentWebcamVideo,
    duration,
    editingKeystrokeSegmentId,
    editingKeyframeId,
    editingPointerId,
    editingSubtitleId,
    editingTextId,
    editorHistory,
    exportHook,
    getKeystrokeTimelineDuration,
    handleDeleteKeystrokeSegment,
    handleDeletePointerSegment,
    handleDeleteSubtitle,
    handleDeleteText,
    handleStartRecording,
    handleTogglePlayPause,
    historyProjectResetRef,
    isCropping,
    isDraggingKeystrokeOverlayRef,
    isRecording,
    isResizingKeystrokeOverlayRef,
    mousePositions,
    onStopRecording,
    persistRef,
    projects,
    rawSetComposition,
    rawSetSegment,
    redo,
    seek,
    segment,
    segmentRef,
    selectedSubtitleIdsRef,
    selectedTextIdsRef,
    setActivePanel,
    setCurrentAudio,
    setCurrentMicAudio,
    setCurrentProjectData,
    setCurrentTime,
    setCurrentVideo,
    setCurrentWebcamVideo,
    setEditingKeyframeId,
    setEditingSubtitleId,
    setEditingTextId,
    setIsKeystrokeOverlaySelected,
    setIsKeystrokeResizeDragging,
    setIsKeystrokeResizeHandleHover,
    setIsPreviewDragging,
    setLoadedClipId,
    setMousePositions,
    setPreviewDuration,
    setSeekIndicatorDir,
    setSeekIndicatorKey,
    setSegment,
    setThumbnails,
    showHotkeyDialog,
    showRawVideoDialog,
    tempCanvasRef,
    undo,
    videoRef,
    webcamConfig,
  } = args;

  useAppEffects({
    segment,
    segmentRef,
    backgroundConfig,
    currentProjectId,
    currentVideo,
    persistRef,
    isRecording,
    showHotkeyDialog,
    onStopRecording,
    handleStartRecording,
    mousePositions,
    composition,
    currentRecordingMode,
    currentRawVideoPath,
    duration,
    videoRef,
    isProcessing: exportHook.isProcessing,
  });

  const handleCloseProject = useCloseProject({
    backgroundConfig,
    currentAudio,
    currentMicAudio,
    currentRawMicAudioPath,
    currentRawVideoPath,
    currentRawWebcamVideoPath,
    currentRecordingMode,
    currentVideo,
    currentWebcamVideo,
    editorHistory,
    historyProjectResetRef,
    isProcessing: exportHook.isProcessing,
    isRecording,
    projects,
    rawSetComposition,
    rawSetSegment,
    setCurrentAudio,
    setCurrentMicAudio,
    setCurrentProjectData,
    setCurrentTime,
    setCurrentVideo,
    setCurrentWebcamVideo,
    setLoadedClipId,
    setMousePositions,
    setPreviewDuration,
    setThumbnails,
    webcamConfig,
  });

  useEditorInteractions({
    segment,
    setSegment,
    currentTime,
    duration,
    backgroundConfig,
    canvasRef,
    videoRef,
    seek,
    isCropping,
    isModalOpen: showRawVideoDialog || exportHook.showExportSuccessDialog,
    editingKeyframeId,
    editingTextId,
    editingSubtitleId,
    editingKeystrokeSegmentId,
    editingPointerId,
    setEditingKeyframeId,
    handleDeleteText,
    handleDeleteSubtitle,
    handleDeleteKeystrokeSegment,
    handleDeletePointerSegment,
    canUndo,
    canRedo,
    undo,
    redo,
    setSeekIndicatorKey,
    setSeekIndicatorDir,
    handleTogglePlayPause,
    mousePositions,
    currentMicAudio,
    currentWebcamVideo,
    tempCanvasRef,
    segmentRef,
    isDraggingKeystrokeOverlayRef,
    isResizingKeystrokeOverlayRef,
    getKeystrokeTimelineDuration,
    setIsPreviewDragging,
    setIsKeystrokeResizeDragging,
    setIsKeystrokeResizeHandleHover,
    setIsKeystrokeOverlaySelected,
    setEditingTextId,
    setEditingSubtitleId,
    setActivePanel,
    handleOverlayDragMove: args.handleOverlayDragMove,
    selectedTextIdsRef,
    selectedSubtitleIdsRef,
    beginBatch,
    commitBatch,
  });

  return { handleCloseProject };
}
