import { useMediaPipelineRecovery } from "@/hooks/useMediaPipelineRecovery";
import { useProjectLifecycle } from "@/hooks/useProjectLifecycle";

type AppProjectLifecycleControllerArgs = Record<string, any>;

export function useAppProjectLifecycleController(args: AppProjectLifecycleControllerArgs) {
  const {
    abortEditorInteractions,
    applyLoadedBackgroundConfig,
    armProjectInteractionShieldRelease,
    backgroundConfig,
    beginProjectInteractionShield,
    canvasRef,
    clearClipMediaCaches,
    clipExportSourcePathCacheRef,
    clipExportWebcamPathCacheRef,
    clipLoadRequestSeqRef,
    composition,
    currentAudio,
    currentMicAudio,
    currentProjectData,
    currentProjectDataRef,
    currentProjectId,
    currentRawMicAudioPath,
    currentRawVideoPath,
    currentRawWebcamVideoPath,
    currentRecordingMode,
    currentTime,
    currentVideo,
    currentWebcamVideo,
    duration,
    exportHook,
    flashRawSavedButton,
    generateThumbnail,
    getMonitors,
    getWindows,
    handleProjectRawVideoPathChange,
    handleStopRecording,
    isPlaying,
    isProjectInteractionShieldVisible,
    isProjectTransitionRef,
    isRecording,
    isSwitchingCompositionClipRef,
    loadClipAssets,
    loadClipMediaIntoEditor,
    loadedClipId,
    monitors,
    mousePositions,
    onProjectLoadedRef,
    previewContainerRef,
    projectInteractionBlockCleanupRef,
    projectInteractionShieldReleaseRef,
    projects,
    projectsPreviewTargetSnapshotRef,
    rawAutoCopyEnabled,
    rawSaveDir,
    rawSetCurrentRawMicAudioPath,
    rawSetCurrentRawWebcamVideoPath,
    rawSetCurrentRecordingMode,
    restoreImageRef,
    seek,
    segment,
    setComposition,
    setCurrentAudio,
    setCurrentMicAudio,
    setCurrentProjectData,
    setCurrentVideo,
    setCurrentWebcamVideo,
    setError,
    setIsProjectInteractionShieldVisible,
    setIsRawActionBusy,
    setLastCaptureFps,
    setLastRawSavedPath,
    setLoadedClipId,
    setPreviewAudioResetKey,
    setRawButtonSavedFlash,
    setShowRawVideoDialog,
    setShowWindowSelect,
    setSpreadFromClipId,
    setWebcamConfig,
    showWindowSelect,
    spreadAnimationTimerRef,
    startNewRecording,
    videoControllerRef,
    webcamConfig,
  } = args;

  const lifecycle = useProjectLifecycle({
    persistRef: args.persistRef,
    isProjectTransitionRef,
    isSwitchingCompositionClipRef,
    canvasRef,
    previewContainerRef,
    restoreImageRef,
    projectsPreviewTargetSnapshotRef,
    currentProjectId,
    projects: {
      projects: projects.projects,
      loadProjects: projects.loadProjects,
      setCurrentProjectId: projects.setCurrentProjectId,
    },
    currentVideo,
    currentAudio,
    currentMicAudio,
    currentWebcamVideo,
    loadedClipId,
    currentProjectData,
    segment,
    composition,
    backgroundConfig,
    mousePositions,
    generateThumbnail,
    duration,
    currentRecordingMode,
    currentRawVideoPath,
    currentRawMicAudioPath,
    currentRawWebcamVideoPath,
    webcamConfig,
    loadClipAssets,
    setComposition,
    setCurrentProjectData,
    monitors,
    getMonitors,
    getWindows,
    isRecording,
    startNewRecording,
    setError,
    showWindowSelect,
    setShowWindowSelect,
    setCurrentRecordingMode: rawSetCurrentRecordingMode,
    setCurrentRawVideoPath: handleProjectRawVideoPathChange,
    setCurrentRawMicAudioPath: rawSetCurrentRawMicAudioPath,
    setCurrentRawWebcamVideoPath: rawSetCurrentRawWebcamVideoPath,
    setLastRawSavedPath,
    setRawButtonSavedFlash,
    projectsDialog: {
      showProjectsDialog: projects.showProjectsDialog,
      setShowProjectsDialog: projects.setShowProjectsDialog,
      handleLoadProject: projects.handleLoadProject,
    },
    isProjectInteractionShieldVisible,
    projectInteractionShieldReleaseRef,
    projectInteractionBlockCleanupRef,
    beginProjectInteractionShield,
    abortEditorInteractions,
    setIsProjectInteractionShieldVisible,
    armProjectInteractionShieldRelease,
    clearClipMediaCaches,
    clipExportSourcePathCacheRef,
    clipExportWebcamPathCacheRef,
    clipLoadRequestSeqRef,
    loadClipMediaIntoEditor,
    setLoadedClipId,
    applyLoadedBackgroundConfig,
    spreadAnimationTimerRef,
    setSpreadFromClipId,
    setLastCaptureFps,
    setWebcamConfig,
    handleStopRecording,
    rawAutoCopyEnabled,
    rawSaveDir,
    flashRawSavedButton,
    setShowRawVideoDialog,
    setShowExportSuccessDialog: exportHook.setShowExportSuccessDialog,
    setIsRawActionBusy,
  });

  onProjectLoadedRef.current = lifecycle.onProjectLoaded;

  useMediaPipelineRecovery({
    currentProjectDataRef,
    currentRawMicAudioPath,
    currentRawVideoPath,
    currentRawWebcamVideoPath,
    currentTime,
    isPlaying,
    projectId: currentProjectId,
    seek,
    segmentDeviceAudioAvailable: segment?.deviceAudioAvailable,
    setCurrentAudio,
    setCurrentMicAudio,
    setCurrentVideo,
    setCurrentWebcamVideo,
    setPreviewAudioResetKey,
    videoControllerRef,
  });

  return lifecycle;
}
