import type { AppNodes } from "./types";

const query = <T extends Element>(selector: string) => document.querySelector<T>(selector)!;

export function collectNodes(): AppNodes {
  return {
    dragRegion: query("#dragRegion"),
    minimizeButton: query("#minimizeButton"),
    closeButton: query("#closeButton"),
    addImagesButton: query("#addImagesButton"),
    queueList: query("#queueList"),
    queueFooter: query("#queueFooter"),
    chooseImageButton: query("#chooseImageButton"),
    chooseFolderButton: query("#chooseFolderButton"),
    showFolderButton: query("#showFolderButton"),
    sourceThumb: query("#sourceThumb"),
    sourceName: query("#sourceName"),
    sourceMeta: query("#sourceMeta"),
    folderName: query("#folderName"),
    polycountRange: query("#polycountRange"),
    polycountValue: query("#polycountValue"),
    modeButtons: [...document.querySelectorAll<HTMLButtonElement>("[data-generation-mode]")],
    autoSegmentSection: query("#autoSegmentSection"),
    autoSegmentInput: query("#autoSegmentInput"),
    generateButton: query("#generateButton"),
    generateLabel: query("#generateLabel"),
    cancelButton: query("#cancelButton"),
    cancelLabel: query("#cancelLabel"),
    segmentButton: query("#segmentButton"),
    statusTitle: query("#statusTitle"),
    statusDetail: query("#statusDetail"),
    statusEta: query("#statusEta"),
    progressTrack: query("#progressTrack"),
    progressFill: query("#progressFill"),
    statusMark: query("#statusMark"),
    stageStatus: query("#stageStatus"),
    readiness: query("#readiness"),
    readinessText: query("#readinessText"),
    emptyCopy: query("#emptyCopy"),
    modelStats: query("#modelStats"),
    resultSummary: query("#resultSummary"),
    resultName: query("#resultName"),
    resultMeta: query("#resultMeta"),
    canvas: query("#modelCanvas"),
    stage: query("#modelStage"),
    viewerToolbar: query("#viewerToolbar"),
    outlineButton: query("#outlineButton"),
    rotateButton: query("#rotateButton"),
    gridButton: query("#gridButton"),
    wireButton: query("#wireButton"),
    fitButton: query("#fitButton"),
    shadingButtons: [...document.querySelectorAll<HTMLButtonElement>(".shading-tool")],
    referencePreview: query("#referencePreview"),
    referencePreviewName: query("#referencePreviewName"),
    referencePreviewImage: query("#referencePreviewImage"),
    referencePreviewClose: query("#referencePreviewClose"),
    confirmDialog: query("#confirmDialog"),
    confirmMessage: query("#confirmMessage"),
    confirmCancel: query("#confirmCancel"),
    confirmAccept: query("#confirmAccept"),
    appToast: query("#appToast"),
  };
}
