//! Language-level phrases used by the deterministic turn policy.

pub(super) const ACTION_TERMS: &[&str] = &[
    "click",
    "type",
    "open",
    "close",
    "move",
    "drag",
    "play",
    "pause",
    "press",
    "select",
    "enter",
    "scroll",
    "focus",
    "minimize",
    "resize",
    "maximize",
    "stop the",
    "cancel the",
    "save",
    "submit",
    "send",
    "copy",
    "paste",
    "undo",
    "redo",
    "rename",
    "create",
    "delete",
    "remove",
    "mute",
    "unmute",
    "toggle",
    "choose",
    "switch",
    "navigate",
    "upload",
    "download",
    "열어",
    "닫아",
    "클릭",
    "입력",
    "눌러",
    "스크롤",
    "이동",
    "저장",
    "저장해",
    "삭제",
    "삭제해",
    "열어줘",
    "닫아줘",
    "클릭해",
    "입력해",
    "눌러줘",
    "스크롤해",
    "이동해",
    "mở",
    "đóng",
    "nhấp",
    "gõ",
    "nhấn",
    "cuộn",
    "di chuyển",
    "lưu",
    "xóa",
];

pub(super) const STOP_PHRASES: &[&str] = &[
    "cancel that",
    "cancel this",
    "cancel it",
    "abort that",
    "abort this",
    "abort it",
    "never mind",
    "nevermind",
    "leave it alone",
    "leave my computer alone",
    "hands off",
    "that s enough",
    "enough now",
    "stop talking",
    "stop speaking",
    "stop everything",
    "stop interacting",
    "stop clicking",
    "stop typing",
    "stop scrolling",
    "stop moving",
    "stop dragging",
    "want you to stop",
    "need you to stop",
    "don t do anything",
    "dont do anything",
    "do not do anything",
    "don t touch my computer",
    "dont touch my computer",
    "do not touch my computer",
    "stop what you re doing",
    "stop the current task",
    "stop controlling",
    "stop using the mouse",
    "stop using my mouse",
    "stop using the keyboard",
    "stop using my keyboard",
    "do not control",
    "don t control",
    "dont control",
    "no more control",
    "no more clicks",
    "no more typing",
    "no more actions",
    "멈춰",
    "중지해",
    "그만해",
    "취소해",
    "컴퓨터 제어를 멈춰",
    "마우스 사용을 멈춰",
    "dừng lại",
    "hãy dừng",
    "ngừng điều khiển",
    "hủy thao tác",
    "thôi đi",
];

pub(super) const READ_ONLY_PHRASES: &[&str] = &[
    "read only",
    "view only",
    "observe only",
    "advice only",
    "answer only",
    "just tell me",
    "only tell me",
    "just explain",
    "only explain",
    "explain why",
    "explain how",
    "what happens if",
    "what if i",
    "what if we",
    "tell me how",
    "how do i",
    "how can i",
    "what should i",
    "should i",
    "walk me through",
    "just advise me",
    "only advise me",
    "let me do it",
    "i ll do it myself",
    "without clicking",
    "without typing",
    "without moving",
    "do not click",
    "don t click",
    "dont click",
    "do not type",
    "don t type",
    "dont type",
    "do not open",
    "don t open",
    "dont open",
    "do not close",
    "don t close",
    "dont close",
    "do not scroll",
    "don t scroll",
    "dont scroll",
    "do not drag",
    "don t drag",
    "dont drag",
    "do not press",
    "don t press",
    "dont press",
    "do not move",
    "don t move",
    "dont move",
    "do not move the mouse",
    "don t move the mouse",
    "dont move the mouse",
    "설명만",
    "읽기만",
    "클릭하지 마",
    "입력하지 마",
    "chỉ giải thích",
    "chỉ đọc",
    "đừng nhấp",
    "đừng nhập",
];
