. (Join-Path $PSScriptRoot "source-fingerprint.ps1")

function Assert-SgtPgoProfile {
    param(
        [Parameter(Mandatory = $true)][string]$Profile,
        [Parameter(Mandatory = $true)][string]$DevelopmentCache,
        [Parameter(Mandatory = $true)][string]$RepoRoot
    )

    $resolved = [IO.Path]::GetFullPath($Profile)
    $allowedRoot = ([IO.Path]::GetFullPath(
        (Join-Path $DevelopmentCache "performance")
    )).TrimEnd('\') + '\'
    if (-not $resolved.StartsWith($allowedRoot, [StringComparison]::OrdinalIgnoreCase) -or
        -not (Test-Path -LiteralPath $resolved -PathType Leaf) -or
        [IO.Path]::GetFileName($resolved) -ne "merged.profdata") {
        throw "-PgoProfile must name a retained merged.profdata below $allowedRoot"
    }
    $profileItem = Get-Item -LiteralPath $resolved
    $profileRoot = $profileItem.Directory
    if (-not $profileRoot.Name.StartsWith("pgo-", [StringComparison]::Ordinal) -or
        ($profileItem.Attributes -band [IO.FileAttributes]::ReparsePoint) -or
        ($profileRoot.Attributes -band [IO.FileAttributes]::ReparsePoint)) {
        throw "-PgoProfile must use a regular retained PGO result directory."
    }
    $reportPath = Join-Path $profileRoot.FullName "pgo-report.json"
    if (-not (Test-Path -LiteralPath $reportPath -PathType Leaf)) {
        throw "PGO report is missing beside the selected profile: $reportPath"
    }
    $report = Get-Content -LiteralPath $reportPath -Raw | ConvertFrom-Json
    if ($report.schemaVersion -ne 2) {
        throw "Unsupported PGO report schema in $reportPath"
    }
    $identity = Get-SgtFileIdentity -Path $resolved
    if ($report.profileArtifact.path -ne $identity.path -or
        [long]$report.profileArtifact.bytes -ne $identity.bytes -or
        $report.profileArtifact.sha256 -ne $identity.sha256) {
        throw "Selected PGO profile bytes do not match their retained report."
    }
    $rustc = (rustc -vV) -join "`n"
    if ($LASTEXITCODE -ne 0 -or $report.rustc -ne $rustc) {
        throw "Selected PGO profile was generated by a different Rust toolchain."
    }
    $source = Get-SgtSourceFingerprint -RepoRoot $RepoRoot
    if ($report.sourceFingerprint -ne $source) {
        throw "Selected PGO profile belongs to a different source state. Regenerate it after the final source change."
    }
    return $resolved
}
