use super::super::compositor::CompositorUniforms;

pub struct CompositorUniformParams {
    pub video_offset: (f32, f32),
    pub video_scale: (f32, f32),
    pub output_size: (f32, f32),
    pub video_size: (f32, f32),
    pub border_radius: f32,
    pub shadow_offset: f32,
    pub shadow_blur: f32,
    pub shadow_opacity: f32,
    pub gradient_color1: [f32; 4],
    pub gradient_color2: [f32; 4],
    pub gradient_color3: [f32; 4],
    pub gradient_color4: [f32; 4],
    pub gradient_color5: [f32; 4],
    pub bg_params1: [f32; 4],
    pub bg_params2: [f32; 4],
    pub bg_params3: [f32; 4],
    pub bg_params4: [f32; 4],
    pub bg_params5: [f32; 4],
    pub bg_params6: [f32; 4],
    pub time: f32,
    pub render_mode: f32,
    pub cursor_pos: (f32, f32),
    pub cursor_scale: f32,
    pub cursor_opacity: f32,
    pub cursor_type_id: f32,
    pub cursor_rotation: f32,
    pub cursor_shadow: f32,
    pub use_background_texture: bool,
    pub bg_zoom: f32,
    pub bg_anchor: (f32, f32),
    pub background_style: f32,
    pub bg_tex_w: f32,
    pub bg_tex_h: f32,
}

pub fn create_uniforms(params: CompositorUniformParams) -> CompositorUniforms {
    let CompositorUniformParams {
        video_offset,
        video_scale,
        output_size,
        video_size,
        border_radius,
        shadow_offset,
        shadow_blur,
        shadow_opacity,
        gradient_color1,
        gradient_color2,
        gradient_color3,
        gradient_color4,
        gradient_color5,
        bg_params1,
        bg_params2,
        bg_params3,
        bg_params4,
        bg_params5,
        bg_params6,
        time,
        render_mode,
        cursor_pos,
        cursor_scale,
        cursor_opacity,
        cursor_type_id,
        cursor_rotation,
        cursor_shadow,
        use_background_texture,
        bg_zoom,
        bg_anchor,
        background_style,
        bg_tex_w,
        bg_tex_h,
    } = params;
    CompositorUniforms {
        video_offset: [video_offset.0, video_offset.1],
        video_scale: [video_scale.0, video_scale.1],
        output_size: [output_size.0, output_size.1],
        video_size: [video_size.0, video_size.1],
        border_radius,
        shadow_offset,
        shadow_blur,
        shadow_opacity,
        gradient_color1,
        gradient_color2,
        gradient_color3,
        gradient_color4,
        gradient_color5,
        time,
        render_mode,
        cursor_pos: [cursor_pos.0, cursor_pos.1],
        cursor_scale,
        cursor_opacity,
        cursor_type_id,
        cursor_rotation,
        cursor_shadow,
        use_background_texture: if use_background_texture { 1.0 } else { 0.0 },
        bg_zoom,
        bg_anchor_x: bg_anchor.0,
        bg_anchor_y: bg_anchor.1,
        bg_style: background_style,
        bg_tex_w,
        bg_tex_h,
        bg_params1,
        bg_params2,
        bg_params3,
        bg_params4,
        bg_params5,
        bg_params6,
    }
}
